# Generated by Django 3.1.1 on 2020-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='git_hub_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
