# Generated by Django 3.1.1 on 2020-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_git_hub_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='git_hub_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
